### ISSUE TITLE
not an ssue,  what is Join Set ?????

### ISSUE THREAD

**Issue by mlotfi2005** [mancioshell/NEMTAB#4]
Hi,
Thanks for this code, I run it , it's working fine, but I did not understand what the purpose of "Join Set" , I click on it nothing happened.

and when you delete a person or a thing, it does not delete in the database, try delete something, then refresh your browser.

Thanks,

**Comment by mancioshell** [comment]
Hi @mlotfi2005 "Join Set" is only a placeholder for any other operation someone wants to implement :)

Fixed delete person operation: https://github.com/mancioshell/NEMTAB/commit/a525611cc699577a00f3dd3d246305b0b69f5b36

Thanks for your contribute ;)

**Comment by mlotfi2005** [comment]
Thank you Sir, I appreciate your help, this is a good tutorial, please let me know if you will do any update or add some new functionality..
